# -*- coding: utf-8 -*-
"""Day2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cJNCMt_QdRa52UiAcxi5tiJvwe4oTGZ8
"""

#  Storing a name in a variable
name = "Twilight"
nameOfPerson = "Yuikana"

# Storing an age in a variable
age = 15

# String
name = "Twilight"

# Integer
age = 15

# Float
height = 147

# Boolean
is_student = False

print(type(name))
print(type(age))
print(type(height))
print(type(is_student))

age = "15"

myAge = int(age)

print(myAge + 2)

name = "Twilight"

print("Haloo, " + name + "!")

print("Haloo, {}!".format(name))

print(f"Haloo, {name}!")

# Personalized Greeting Program

# Step 1: Ask for user details
name = input("What is your name? ")
age = int(input("How old are you? "))
color = input("What is your favorite color? ")

# Step 2: Generate a personalized greeting message
print("\n---- Personalized Greeting ----")
print(f"Hello, {name}! 👋")
print(f"You are {age} years old and {color} is a beautiful color!")
print("You're now ready to start your Python adventure 🚀🐍")