# -*- coding: utf-8 -*-
"""Day5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aZ4V5QJxh1Ej_7E7ghDD2ZTrQ4mrgV-s
"""

for variable in range(0, 10, 1):
    pass  # Menandakan blok ini sengaja dikosongkan agar tidak error

for i in range(5, 0, -1):
    print(i)

count = 0
while count < 5:
    print(count)
    count += 1

import time

for i in range(10, 0, -2):
  print(i)
  time.sleep(2)
print("Happy New Year!")

# Countdown Timer

import time

# Step 1: Get user input for countdown start
start = int(input("Enter the number to start the countdown from: "))

# Step 2: Countdown using a while loop
print("\n--- Countdown Begins ---")
while start > 0:
  print(start)
  time.sleep(1)
  start -= 1

# Step 3: Print final message
print("Countdown Complete!")