# -*- coding: utf-8 -*-
"""FirstCode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1scrSyCNbfbEcf4l3vtJbF_QVQLEpbvCW
"""

print("Hello, Twilight!")

name = "Twilight"
age = 15
height = 147.5
is_writer = True

print("Name: ", name)
print("Age:", age)
print("Height:", height)
print("Is writer?", is_writer)

user_name = input("Whats your name? ")
print("Welcome, " + user_name+ "^^")

x = 3
y = 10

print(x + y)
print(y - x)
print(x * y)
print(y / x)
print(y // x)
print(y % x)
print(y ** x)

age = int(input("Enter your age: "))

if age >= 18:
  print("You are an adult.")
elif age >= 13:
  print("You are an teenager.")
else:
  print("You are a minor.")

count = 0
while count < 10:
  print("Count is:", count)
  count += 1

video_games = ["Game 1", "Game 2", "Game 3"]

for game in video_games:
  print(game)

video_games = ["Game 1", "Game 2", "Game 3"]

print(video_game[0])
print(video_game[1])
print(video_game[2])

video_games.append("Game 4")

print(video_games)

video_games[3] = "Game 5"

print(video_games)

def say_hello(person_name):
  print("Hello, " + person_name + ". From your first function^^")

say_hello("Tiwi")

def multiply(a, b):
  return a*b

result = multiply(5, 3)

print("Result: ", result)

import random

secret_number = random.randint(1, 5)
attempts = 2

print("I'm thinking a number between 1 and 5")

while attempts > 0:
  guess = int(input("Take a guess: "))
  if guess == secret_number:
    print("Congratulations! You guessed the number!")
    break
  elif guess < secret_number:
    print("Too low! Try again...")
  else:
    print("Too high! Try again...")
  attempts -= 1

if attempts == 0:
  print("Sorry, you've run out attempts. The secret number was:", secret_number)
  