# -*- coding: utf-8 -*-
"""Day3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aH6hlkpa3yHnau9fIXGP15R4n4mcmLN6
"""

name = input("Enter your name: ")
print(f"Hello, {name}")

num1 = int(input("Enter a number: "))
num1 = str(num1)
print(f"Number doubled: {num1 * 2}")

num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))
result = num1 + num2

print(f"The sum of {num1} and {num2} is {result}")

a = 6
b = 9

print(f"Addition: {a + b}")
print(f"Subtraction: {a - b}")
print(f"Multiplication: {a * b}")
print(f"Division: {a / b}")
print(f"Floor Division: {a // b}")
print(f"Modulus: {a % b}")
print(f"Exponentiation: {a ** b}")

# Simple Calculator

# Step 1: Get user input for two numbers
number1 = float(input("Enter the first number: "))
number2 = float(input("Enter the second number: "))

# Step 2: Perform arithmetic operation
addition = number1 + number2
subtraction = number1 - number2
multiplication = number1 * number2
division = number1 / number2 if num2 != 0 else "Cannot divide by zero"

# Step 3: Display the results
print("\n--- Calculator Results ----")
print(f"Addition:{number1} + {number2} = {addition}")
print(f"Subtraction:{number1} - {number2} =  {subtraction}")
print(f"Multiplication:{number1} x {number2} =  {multiplication}")
print(f"Division:{number1} / {number2} =  {division}")
